### ISSUE TITLE
how do I limit access ?

### ISSUE THREAD

**Issue by dorongutman** [fiverr/rollout_service#10]
I need to run this app just for the dashboard, and I don't want it to be publicly accessable.
How can I limit the access (even for reads) only to the server that's going to run the dashboard ? 
I want to run both (rollout_service and rollout_dashboard) as heroku apps, so I can't limit the ip addresses as they're not fixed.

**Comment by yossi-eynav** [comment]
Hi @dorongutman !
I think that the best way to do that is to allow restriction even to the reads using google authentication.

So even if the service will be publicly expose, it would be meaningless. 
let me know what you think

**Comment by dorongutman** [comment]
@yossi-eynav yes that sounds like a good approach

**Comment by yossi-eynav** [comment]
@dorongutman we made many changes here, now you can add whatever you like in your RACK app

**Comment by nsal-ai** [comment]
Hi guys is it safe to allow  fiverr authentication to access your github profile as a seller? What would be the implications?
