### ISSUE TITLE
500 error when checking if a feature is active for a user

### ISSUE THREAD

**Issue by Jaspaul** [fiverr/rollout_service#5]
I've created a new feature `test`, which you can see at https://sir-feature-flags.herokuapp.com/api/v1/features/test

You'll notice that there are 10 users that have access to the test feature.

When I attempt to access https://sir-feature-flags.herokuapp.com/api/v1/features/test/1/active to check if the feature is active for the user with id 1, I get a 500 server error.

I'm not sure where I'm going wrong.

**Comment by yossi-eynav** [comment]
hey @Jaspaul !
I pushed a fix https://github.com/fiverr/rollout_service/commit/00f0a8a93aa0e4f661c2dd393598ea53c9ff18f3, please rebase master and re-deploy.

**Comment by Jaspaul** [comment]
@yossi-eynav I've rebased and now both endpoints are failing with a 500 error.

**Comment by yossi-eynav** [comment]
@Jaspaul 
can you share the exception stack?
